global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Threading;
global using TrafficSimulation.Core.Extensions;
global using static TrafficSimulation.Core.Extensions.ObjectExtensions;
global using Object = UnityEngine.Object;
